# [LEARN] sonar-project.properties configure l'analyse SonarCloud.
# [LEARN] SonarCloud scanne ton code et remonte :
# [LEARN]   - Les bugs potentiels (code qui peut crasher)
# [LEARN]   - Les code smells (code difficile à maintenir)
# [LEARN]   - Les vulnérabilités de sécurité
# [LEARN]   - La couverture de tests (% de code testé)
# [LEARN]
# [LEARN] sonar.projectKey et sonar.organization se trouvent sur sonarcloud.io
# [LEARN] après avoir créé le projet en important le repo GitHub.

sonar.projectKey=Moise20_NestJS-backEnd-projetReact
sonar.organization=moise20

sonar.projectName=NestJS Backend — E-Commerce Blog
sonar.projectVersion=1.0

sonar.sources=src
sonar.exclusions=**/*.spec.ts,**/node_modules/**,**/dist/**,**/coverage/**

sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
